#Stage 1
FROM node:16-alpine as build-step
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
COPY frontend/src ./src
COPY frontend/public ./public
RUN npm install
RUN npm run build

#Stage 2
# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf