version: '3.9'

services:
    meta_app:
       build: .
       restart: always
       ports:
           - "80:5000"
       environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
            POSTGRES_DB: ${POSTGRES_DB}
       links:
          - postgres
       depends_on:
          - postgres
       container_name: meta_app
    
    postgres:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
            POSTGRES_DB: ${POSTGRES_DB}
        
        volumes:
            - pgdata:/var/lib/postgresql/data
        container_name: meta_datastore
volumes:
  pgdata: {}